chaincodelabs/seminars

- p2p/README.md
> add Bitcoin over Tor isnt a good idea paper to p2p

- segwit/README.md
> update segwit readme

- README.md
- mining-network-prop/README.md
- p2p/README.md
- wallet-psbt/README.md
- welcome-to-the-bitcoin-protocol/README.md
Add welcome study group and update other resources including 2019 seminar videos
> Bitcoin: updates for 2020

- wallet-psbt/README.md
This PR proposes to add a recent practical update by Andrew Chow. Reading time and tag TBC. I found it helpful for reviewing PRs like [Bitcoin Core PR16528](https://github.com/bitcoin/bitcoin/pull/16528). Endorsement by Russ here: https://github.com/bitcoin/bitcoin/pull/16528#issuecomment-611938384
> wallet-psbt: add native descriptor wallets

- lightning-routing/ANSWERS.md
- lightning-routing/README.md
it would be nice to have but does not fit with the section
> rm neutrino

- future-of-lightning/ANSWERS.md
- future-of-lightning/README.md
- lightning-how-the-pieces-fit-together/README.md
- lightning-limitations/ANSWERS.md
- lightning-limitations/README.md
- lightning-routing/README.md
move RV routing from future to routing
add payment points to future and rm redundant probing
add DH key-exchange and HMAC to intro
add discussion questions to limitations
> lightning fixups

- mining-network-prop/ANSWERS.md
- mining-network-prop/README.md
- p2p/ANSWERS.md
- p2p/README.md
move outdated discussion question from block prop to p2p tx section
update discussion questions
cull overlapping resources
> mining and tx p2p section updates:

- p2p/README.md
Updated chapter includes the correct number of DNS seeds (see https://github.com/bitcoinbook/bitcoinbook/pull/739).
> Update link to the "The Bitcoin Network" chapter in Mastering Bitcoin

- mining-network-prop/ANSWERS.md
- mining-network-prop/README.md
Now updated to the more accurate "stale blocks".
> Update terminology: orphan blocks

- lightning-protocol-development/payment-channels-htlcs.md
sub outdated rusty article for derpturkey
> sub outdated rusty article for derpturkey

- lightning-protocol-development/lightning-routing.md
h/t @Caralie for the audio fix
> update path finding video with audio fix

- lightning-protocol-development/payment-channels-htlcs.md
> Fix Typo flexiblity to flexibility

- bitcoin-protocol-development/script-wallets.md
> add taproot to week 5

- lightning-protocol-development/lightning-routing.md
> add blinded routing

- lightning-protocol-development/future-of-lightning.md
onion messages, offers, route blinding, liquidity ads, peer backups, minisketch
Mixing in some in-progress projects and a few that should probably be in there already.
> add future of lightning content

- bitcoin-protocol-development/p2p.md
The current question focuses on an extremely specific nuance of the connection logic for IBD. This commit proposes updating the question to focus on a more significant mechanism of a bitcoin core node.
> Update P2P discussion question

- bitcoin-protocol-development/mining-network-prop.md
The transcript for "Mining: No Good, The Bad, and The Ugly"  [is now available](https://github.com/bitcointranscripts/bitcointranscripts/pull/112).
> add transcript link for Mining: No Good, The Bad, and The Ugly

- bitcoin-protocol-development/mining-network-prop.md
> advances in block prop fixup

- bitcoin-protocol-development/welcome-to-the-bitcoin-protocol.md
The original link returns 404.
> Fix link to 'Security Models with John Newbery'

- bitcoin-protocol-development/mining-network-prop.md
Adds a question on mempool divergence & break-down of transaction standardness
> tx standardness + mempool divergence

- bitcoin-protocol-development/script-wallets.md
for me the current link doesn't work
> update Intro Bitcoin Core fee estimation link

- lightning-protocol-development/future-of-lightning.md
The transcript version helped me find the answer to the fee question, as it came in part of the video after the specified 26 minutes.
> improve(future-of-lightning.md): Replace Youtube URL with Bitcoin Transcripts

- bitcoin-protocol-development/welcome-to-the-bitcoin-protocol.md
Changed the broken link for "Bitcoin's Security Model: A Deep Dive" in Welcome-to-the-bitcoin-protocol.md file
> update material link 6 in Welcome to BPD
